### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by royvegard** [usnistgov/AGA8#14]
Add a (preferably open source compatible) license.

I would like to publish the Rust version on https://crates.io, but that requires a license.

**Comment by ianhbell** [comment]
Can they do a MIT* license, where the * indicates some NIST-specific requirements on top of the MIT license?

**Comment by royvegard** [comment]
Yes. The requirement is only that a license is defined, and not the actual contents of the license. We can use the `license-file` key to point to a custom license file.

From The Cargo Book:
```
# This is an SPDX 2.1 license expression for this package. Currently
# crates.io will validate the license provided against a whitelist of
# known license and exception identifiers from the SPDX license list
# 3.6. Parentheses are not currently supported.
#
# Multiple licenses can be separated with a `/`, although that usage
# is deprecated. Instead, use a license expression with AND and OR
# operators to get more explicit semantics.
license = "..."

# If a package is using a nonstandard license, then this key may be specified in
# lieu of the above key and must point to a file relative to this manifest
# (similar to the readme key).
license-file = "..."
```

```
// String of the license for the package.
// May be null. crates.io requires either `license` or `license_file` to be set.
"license": null,
// String of a relative path to a license file in the crate.
// May be null.
"license_file": null,
```

**Comment by royvegard** [comment]
@ianhbell, have you thought more about adding a license file?

**Comment by ianhbell** [comment]
I'm making inquiries with our legal folks...

**Comment by Ledragon** [comment]
Hey, thanks for the library.
Interested in knowing the licensing terms as well ;-)

**Comment by Ledragon** [comment]
FYI, I found the following reference:
https://asgmt.com/paper/2019/page/2/

In [this pdf](https://asgmt.com/wp-content/uploads//Papers/Speed%20of%20Sound%20in%20Natural%20Gas%20From%20AGA%2010%20to%20AGA%208.pdf), page 3, you can read this:

>The code was translated into both Fortran and C, and all three codes are made freely available from AGA or NIST6. This work > > was done at NIST on the condition that the material would not be copyrighted and would be made available to all without > charge so that others could use and/or modify the code as necessary for any application.

**Comment by Ledragon** [comment]
Thanks!
