### ISSUE TITLE
AGA8 density calculation for CO2 in the boundary area between liquid and vapor phases

### ISSUE THREAD

**Issue by PAFF777** [usnistgov/AGA8#25]
Thanks for the AGA8 excel spreadsheet. It is very useful for gas property calculations.
By the way, I recently noticed that the CO2 (100%) density calculation with AGA8 is significantly different from the calculation results on the NIST site, especially in the liquid and vapor phase boundary areas.
For example, at a temperature of -40F and a pressure of 260psia, the density of CO2 (100%) is 3.56 lbm/ft3, but the NIST calculation result is 69.837 lbm/ft3, which matches the CO2 phase diagram as liquid phase.
I noticed that the vapor-liquid boundary line from the critical point to the triple point calculated with AGA8 is rises to an area of higher pressure as shown in red line on the attached picture. 

Best Regards,

![liquid-vapor Boundary for CO2](https://github.com/usnistgov/AGA8/assets/150590187/0fd69a51-822d-4fb4-842a-383155742b23)

**Comment by EricLemmon** [comment]
When reporting calculations from "AGA8", you need to be specific if you mean the DETAIL method given in Part 1 of that standard or the GERG method given in Part 2.  The CO2 pure fluid equation in the GERG method is quite accurate and does not show this behavior.  The CO2 equation in the DETAIL method should never be used in the liquid phase nor for phase boundary calculations due to issues such as this.

**Comment by PAFF777** [comment]
Thank you Eric for your prompt response. 
I used GERG method as shown in the attached pic below (left side is GERG' result as you know and right side is NIST page result).
I would appreciate it if you could inform when you find out why there is such a difference in the calculation results.
Best Regards,
![Density Calculation](https://github.com/usnistgov/AGA8/assets/150590187/c1358701-4c55-4a10-8947-244e37a08199)
.

**Comment by EricLemmon** [comment]
This is happening because the xls file does not know where the saturation boundaries are and the state it returns is actually in the vapor phase but beyond the saturated pressure.  There's a big red warning on the spreadsheet that discusses this:

> ***WARNING***
> No checks are made in the calculations below to ensure that the state point is single-phase.  It is up to the user to locate the phase boundaries.
> Calculated values for states that are actually 2-phase will be returned as metastable states, and will not be correct.

**Comment by PAFF777** [comment]
Hi Eric,
I greatly appreciate the time you spent with this issue. 
You are right. I think I can solve this problem by setting a boundary between the liquid and the vapor phase.
Best Regards,
