### ISSUE TITLE
Discrepancy in GERG2008 dPdD2

### ISSUE THREAD

**Issue by royvegard** [usnistgov/AGA8#8]
After commit ab8fb61a1e4bb73a90f552458763077a80660343 there is a discrepancy in the dPdD2 result:

```
d^2(P)/d(rho)^2 [kPa/(mol/l)^2]:    1130.481239114938 != 1129.526655214841
```

Maybe related to #6 since it's the same parameter.

It looks like ab8fb61a1e4bb73a90f552458763077a80660343 is making some tolerances more strict, so perhaps 1129.526... is the more correct result.

**Comment by ianhbell** [comment]
Actually, the "correct" approach is something entirely different: put in a density and temperature rather than pressure and temperature.  This removes the iterative calculation entirely, ensuring that the test will give the same answer every time, without a question of the convergence criterion.  Do you think you could make that change to the tests?

**Comment by royvegard** [comment]
I failed to mention that the test I'm running is the main() function at the bottom of GERG2008.cpp. I'm assuming that the reference numbers in the printfs should match the calculated values. That test uses temperature and pressure as inputs.

After looking a bit closer I see that the change in tolerances is a red herring, as those are reverted back a few days later by 2975b65bb5131eaac0ac752118c26e30c7a18635. And if the tolerance changes were significant, surely there should have been a discrepancy in the calculation of D also.

This is the change that actually causes the discrepancy (it's in the same commit as originally claimed):
https://github.com/usnistgov/AGA8/commit/ab8fb61a1e4bb73a90f552458763077a80660343#r35403344

So I guess it boils down to: is this change correct?

The same change is applied to the VB version in 6b066ef58da43760734f8296d27e923cde2998d6.

**Comment by ianhbell** [comment]
@royvegard I don't think we have been acquainted before, but I must say I really appreciate your digging into the code and finding this small discrepancy.  I'll make sure that Eric Lemmon is in contact with you for future testing :)

My guess, to be confirmed, is that the "right" value needs to be updated as a consequence of the change you noted.

**Comment by EricLemmon** [comment]
I made a special version of Refprop so that I could enter 21 components.  With the same T and P as used in the test code, I was able to verify that the correct value is 1129.526655...
